language: php

php:
  - 5.4
  - 5.5
  - 5.6
#  - hhvm

env:
  - $SYMFONY_VERSION='2.3.*'
  - $SYMFONY_VERSION='2.4.*'
  - $SYMFONY_VERSION='2.5.*'
  - $SYMFONY_VERSION='2.6.*'

matrix:
    allow_failures:
        - php: hhvm

before_install: |
    # needed for the UML container
    sudo apt-get install -qq -y slirp aufs-tools cgroup-lite

    # prepare docker dir for aufs mount
    sudo mkdir -p /var/lib/docker

    # download usermode linux kernel for docker
    curl -sLo linux https://github.com/jpetazzo/sekexe/raw/master/uml
    chmod +x linux

    # download docker
    curl -sLo docker https://get.docker.io/builds/Linux/x86_64/docker-1.3.2
    chmod +x docker

    # ---------------------------------------------------------------------------
    chmod +x tests.sh
    chmod +x run.sh

install:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install

script: ./run.sh
